[skin]
    description = Sky Blue Dynamic
    truecolor=true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ─
    dvert = │
    dlefttop = ┌
    drighttop = ┐
    dleftbottom = └
    drightbottom = ┘
    dtopmiddle = ┬
    dbottommiddle = ┴
    dleftmiddle = ├
    drightmiddle = ┤

[core]
    _default_ = lightgray;#12488b
    selected = black;cyan
    marked = yellow;#12488b
    markselect = yellow;cyan
    gauge = white;black
    input = black;cyan
    inputunchanged = gray;cyan
    inputmark = cyan;black
    disabled = gray;lightgray
    reverse = black;lightgray
    commandlinemark = black;lightgray
    header = yellow;#12488b
    inputhistory =
    commandhistory =
    shadow = gray;black

[dialog]
    _default_ = black;lightgray
    dfocus = black;cyan
    dhotnormal = #12488b;lightgray
    dhotfocus = #12488b;cyan
    dtitle = #12488b;lightgray

[error]
    _default_ = white;#ff5555
    errdfocus = black;lightgray
    errdhotnormal = yellow;#ff5555
    errdhotfocus = yellow;lightgray
    errdtitle = yellow;#ff5555

[filehighlight]
    directory = white;
    executable = brightgreen;
    symlink = lightgray;
    hardlink =
    stalelink = bright#ff5555;
    device = brightmagenta;
    special = black;
    core = #ff5555;
    temp = gray;
    archive = brightmagenta;
    doc = brown;
    source = cyan;
    media = green;
    graph = brightcyan;
    database = bright#ff5555;

[menu]
    _default_ = white;cyan
    menusel = white;black
    menuhot = yellow;cyan
    menuhotsel = yellow;black
    menuinactive = black;cyan

[popupmenu]
    _default_ = white;cyan
    menusel = yellow;black
    menutitle = yellow;cyan

[buttonbar]
    hotkey = white;black
    button = black;cyan

[statusbar]
    _default_ = black;cyan

[help]
    _default_ = black;lightgray
    helpitalic = #ff5555;lightgray
    helpbold = #12488b;lightgray
    helplink = black;cyan
    helpslink = yellow;#12488b
    helptitle = #12488b;lightgray

[editor]
    _default_ = lightgray;#12488b
    editbold = yellow;green
    editmarked = black;cyan
    editwhitespace = bright#12488b;#12488b
    editnonprintable = ;black
    editlinestate = white;cyan
    bookmark = white;#ff5555
    bookmarkfound = black;green
    editrightmargin = bright#12488b;black
#    editbg = lightgray;
#    editframe = lightgray;
    editframeactive = white;
    editframedrag = green;

[viewer]
    _default_ = lightgray;#12488b
    viewbold = yellow;#12488b
    viewunderline = bright#ff5555;#12488b
    viewselected = yellow;cyan

[diffviewer]
    added = white;green
    changedline = #12488b;cyan
    changednew = #ff5555;cyan
    changed = white;cyan
    removed = white;#ff5555
    error = #ff5555;lightgray

[widget-panel]
    sort-up-char = '
    sort-down-char = .
    filename-scroll-left-char = {
    filename-scroll-right-char = }

[widget-editor]
    window-state-char = *
    window-close-char = X
